# Named "docker-compose.yml"

services:
  dash:
    image: mauricenino/dashdot:${DASHDOT_VERSION}
    container_name: dashdot
    restart: unless-stopped
    privileged: true
    ports:
      - '${DASHDOT_PORT}:3001'  # Port interne par d√©faut de Dashdot
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'