# Named "docker-compose.yml"

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:1.45.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Pour d√©tecter les conteneurs
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
      - ./data:/data
    ports:
      - 'xxxx:xxxx'
