# Named "docker-compose.yml"

services:
  n8n:
    image: n8nio/n8n:${N8N_VERSION}
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${N8N_PORT_EXTERNAL}:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - GENERIC_TIMEZONE=Europe/Paris
      - N8N_HOST=${HOST_IP}
      - N8N_PORT=5678       # Config applicative (Don't change)
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://${HOST_IP}:${N8N_PORT_EXTERNAL}/
      - N8N_SECURE_COOKIE=false
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
    volumes:
      - ./data:/home/node/.n8n