# Named "docker-compose.yml"

services:
  nocodb:
    image: nocodb/nocodb:${NOCODB_VERSION}
    container_name: nocodb
    restart: unless-stopped
    ports:
      - "${NOCODB_PORT}:8080"
    volumes:
      - ./data:/usr/app/data
    environment:
      - NC_AUTH_JWT_SECRET=${NOCODB_JWT_SECRET}