# Named "docker-compose.yml"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:${PIHOLE_VERSION}
    ports:
      - "${PIHOLE_DNS_PORT}:53/tcp"
      - "${PIHOLE_DNS_PORT}:53/udp"
      - "${PIHOLE_WEB_PORT}:80/tcp"
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped