# Named "docker-compose.yml"

services:
  portainer:
    image: portainer/portainer-ce:2.33.5
    container_name: portainer
    restart: unless-stopped
    ports:
      - "xxxx:xxxx"
      - "xxxx:xxxx"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    security_opt:
      - no-new-privileges:true
