# Named "docker-compose.yml"

services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer
    restart: unless-stopped
    ports:
      - "${PORTAINER_PORT}:9000"
      - "${PORTAINER_AGENT_PORT}:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    security_opt:
      - no-new-privileges:true