# Named "docker-compose.yml"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:${UPTIMEKUMA_VERSION}
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${UPTIMEKUMA_PORT}:3001"
    restart: unless-stopped