# Named "docker-compose.yml"

services:
  vaultwarden:
    image: vaultwarden/server:${VAULTWARDEN_VERSION}
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "${VAULTWARDEN_PORT}:80"
      - "${VAULTWARDEN_WEBSOCKET_PORT}:3012"
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: "${VAULTWARDEN_ADMIN_TOKEN}"
    volumes:
      - ./data:/data